export const chartConfig = {
  appreciationData: [
    { month: "Jan", value: 100 },
    { month: "Feb", value: 102 },
    { month: "Mar", value: 105 },
    { month: "Apr", value: 108 },
    { month: "May", value: 110 },
    { month: "Jun", value: 115 },
    { month: "Jul", value: 118 },
    { month: "Aug", value: 122 },
    { month: "Sep", value: 125 },
    { month: "Oct", value: 128 },
    { month: "Nov", value: 132 },
    { month: "Dec", value: 135 },
  ],
  portfolioData: [
    { name: "Commercial", value: 35 },
    { name: "Residential", value: 40 },
    { name: "Mixed Use", value: 25 },
  ],
}

export const mockProperties = [
  {
    id: "1",
    city: "Mumbai",
    name: "Prestige Corporate Tower",
    type: "Commercial",
    rentYield: 7.5,
    minInvestment: 50000,
    appreciation: 12,
    image: "/properties/1.jpg",
  },
  {
    id: "2",
    city: "Bangalore",
    name: "Green Valley Residences",
    type: "Residential",
    rentYield: 6.2,
    minInvestment: 40000,
    appreciation: 10,
    image: "/properties/2.jpg",
  },
  {
    id: "3",
    city: "Delhi",
    name: "Downtown Plaza",
    type: "Mixed Use",
    rentYield: 8.1,
    minInvestment: 60000,
    appreciation: 14,
    image: "/properties/3.jpg",
  },
  {
    id: "4",
    city: "Hyderabad",
    name: "Tech Park Hub",
    type: "Commercial",
    rentYield: 7.8,
    minInvestment: 55000,
    appreciation: 13,
    image: "/properties/4.jpg",
  },
  {
    id: "5",
    city: "Pune",
    name: "Riverside Apartments",
    type: "Residential",
    rentYield: 5.9,
    minInvestment: 35000,
    appreciation: 9,
    image: "/properties/5.jpg",
  },
  {
    id: "6",
    city: "Chennai",
    name: "Marina Heights",
    type: "Residential",
    rentYield: 6.5,
    minInvestment: 42000,
    appreciation: 11,
    image: "/properties/6.jpg",
  },
]

export const mockPortfolio = {
  totalValue: 425000,
  monthlyRent: 2150,
  appreciationValue: 52000,
  holdings: [
    { propertyName: "Prestige Corporate Tower", units: 5, invested: 250000, currentValue: 280000, rent: 1050 },
    { propertyName: "Green Valley Residences", units: 3, invested: 120000, currentValue: 135000, rent: 650 },
    { propertyName: "Tech Park Hub", units: 2, invested: 55000, currentValue: 62000, rent: 450 },
  ],
}
